const vitamin_list = ['report:protein-intake',
                              'report:carbohydrate-intake',
                              'report:caffeine-metabolite-ratio',
                              'report:caffeine-consumption',
                              'report:egg-allergy',
                              'report:peanuts-allergy',
                              'report:milk-allergy',
                              'report:vitamin-a',
                              'report:vitamin-b12',
                              'report:vitamin-d',
                              'report:vitamin-e',
                              'report:response-to-vitamin-e-supplementation',
                              'report:folate',
                              'report:calcium',
                              'report:magnesium',
                              'report:phosphorus',
                              'report:iron',
                              'report:alpha-linolenic-acid',
                              'report:beta-carotene',
                              'report:blood-glucose'];

module.exports = vitamin_list;